spring:
  application:
    name: lcx-ai-code-mother

server:
  port: 8123
  servlet:
    context-path: /api


springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.lcx.lcxaicodemother.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
